### ISSUE TITLE
Remove RMI logo from header

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta.pkgdown.template#2]
Currently, we have the RMI logo in our `README` files. We don't need it to also appear in the header, it appears kind of crammed:

<img width="1160" alt="Screen Shot 2022-11-29 at 4 03 36 PM" src="https://user-images.githubusercontent.com/8741309/204564777-31868df0-8139-4187-8734-47f5b94887aa.png">

**Comment by cjyetman** [comment]
closed in 34aa31236ca3d90a78ca190f4ab6aa26d2a747c1
